# Generated by Django 4.2.2 on 2023-06-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0002_poem_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
