# Generated by Django 4.2.2 on 2023-06-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0003_poem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='excerpt',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
