# Generated by Django 4.2.2 on 2023-06-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0005_alter_poem_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='category',
            field=models.CharField(choices=[('EURO', 'European'), ('ASIA', 'Asian'), ('AMERICA', 'AMERICAN'), ('AFRICA', 'African'), ('OCEANIA', 'Oceania')], default='EURO', max_length=10),
        ),
    ]
